import React, { useRef } from 'react';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

// IMPORTANT: Register the hook and the plugin
gsap.registerPlugin(ScrollTrigger);

export default function MotionHero() {
  const container = useRef();

  useGSAP(() => {
    // Refresh ScrollTrigger to catch the correct layout height
    ScrollTrigger.refresh();

    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: container.current,
        start: "top top",
        end: "+=150%", 
        pin: true,
        scrub: 1.2,
        // markers: true, // Uncomment this to see if the trigger is firing
      }
    });

    // 1. Target the specific classes generated by splitText
    tl.to(".char", {
      scale: 10,
      opacity: 0,
      stagger: 0.03,
      ease: "power2.inOut"
    })
    
    // 2. Target the sub-char class
    .from(".sub-char", {
      yPercent: 110,
      opacity: 0,
      stagger: 0.05,
      ease: "expo.out"
    }, "-=0.4"); 

    // 3. Parallax Background
    gsap.to(".parallax-bg", {
      y: (i) => -300 * (i + 1),
      scrollTrigger: {
        trigger: container.current,
        start: "top top",
        scrub: true
      }
    });
  }, { scope: container });

  const splitText = (text, cls) => text.split("").map((char, i) => (
    <span key={i} className={`${cls} inline-block`}>
      {char === " " ? "\u00A0" : char}
    </span>
  ));

  return (
    <section ref={container} className="relative h-screen flex flex-col items-center justify-center overflow-hidden bg-gradient-to-br from-[#FF0080] via-[#7928CA] to-[#4FACFE]">
      {/* Parallax Vertical Bars */}
      <div className="parallax-bg absolute left-[15%] w-px h-full bg-white/20" />
      <div className="parallax-bg absolute right-[25%] w-1 h-full bg-white/30" />

      <div className="main-title overflow-hidden px-10 relative z-10">
        <h1 className="text-[18vw] font-black text-white leading-none tracking-tighter uppercase">
          {splitText("AI-VERSE", "char")}
        </h1>
      </div>

      <div className="sub-title overflow-hidden mt-10 relative z-10">
        <h2 className="text-[5vw] font-bold text-white tracking-[0.2em] uppercase">
          {splitText("JAN 04—06 2025", "sub-char")}
        </h2>
      </div>

      <div className="fixed bottom-10 right-10 z-[120]">
        <button className="bg-[#B7FF00] px-10 py-5 font-black uppercase text-sm shadow-[0_0_40px_rgba(183,255,0,0.4)]">
          Get Passes
        </button>
      </div>
    </section>
  );
}